// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf8mrmn8IuY_iz05MmBAREFditF_PERoE',
    appId: '1:716500901593:web:13ff39bbaf2e4d275a28c8',
    messagingSenderId: '716500901593',
    projectId: 'acm-apps-59085',
    authDomain: 'acm-apps-59085.firebaseapp.com',
    storageBucket: 'acm-apps-59085.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvJx6haAbOwY_ArSAZec4EPurfoV3cWXs',
    appId: '1:716500901593:android:7ad1ca077c53367a5a28c8',
    messagingSenderId: '716500901593',
    projectId: 'acm-apps-59085',
    storageBucket: 'acm-apps-59085.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf8mrmn8IuY_iz05MmBAREFditF_PERoE',
    appId: '1:716500901593:web:dd396c49680b66e45a28c8',
    messagingSenderId: '716500901593',
    projectId: 'acm-apps-59085',
    authDomain: 'acm-apps-59085.firebaseapp.com',
    storageBucket: 'acm-apps-59085.firebasestorage.app',
  );
}
